sudo: required

services:
  - docker

language: node_js
node_js:
  - "5"

before_install:
  - docker build -t chrisjstevenson/volumizr-web-app .
  - docker run -p 9005:8080 -d chrisjstevenson/volumizr-web-app
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push chrisjstevenson/volumizr-web-app